### ISSUE TITLE
someStreetAreaId Link is does not work / empty

### ISSUE THREAD

**Issue by Nastras** [benzman81/my-muell-ical#1]
Hello Marcus,

I wanted to test your calendar tool unfortunately I am missing the data of someStreetAreaId

LG Nastra

**Comment by benzman81** [comment]
Works for my city `https://mymuell.jumomind.com/mmapp/api.php?r=streets&city_id=35105`

**Comment by Nastras** [comment]
Thank you for your quick reply. Now it worked and I found the ID for my street.

But I can't get the calendar via safari. In iCal as a subscription add it also does not want.

Via iCal I get the following error:
<img width="287" alt="Bildschirmfoto 2021-01-09 um 19 00 50" src="https://user-images.githubusercontent.com/27686185/104105356-b5ed9c00-52ad-11eb-9420-5c3acfe55b78.png">


Via Safari I get the following error:
<img width="617" alt="Bildschirmfoto 2021-01-09 um 19 06 43" src="https://user-images.githubusercontent.com/27686185/104105395-0d8c0780-52ae-11eb-8f34-a393b91b142f.png">

This is the url I tried. Is there still an error? 
http://myserverandport/calendar.ical?city_id=XXXXX&area_id=XXXXX

I must be doing something else wrong or?

Thank you!

**Comment by benzman81** [comment]
Yes 🙈 may you should host this project as an app 😉 this is just the code you can run as a server. You can host it yourself, i.e. on heroku. Then you have a working url you can use in the form you already tried. But „myserverandport“ is not an existing server 😉

**Comment by Nastras** [comment]
I almost thought it 😂
I don't have an iCal server and I don't know anything about Heroku.

Is it complicated to set up something like this?

**Comment by benzman81** [comment]
No, just create an heroku account and link this repo. It will build und start it and give you an url.

**Comment by Nastras** [comment]
Ok, I have created an account now but I have no idea where to do what and how in heroku? Would be great if you can help me again.

**Comment by benzman81** [comment]
In the heroku dashboard you create a new app and enter a name and choose a region. Next page you choose github as deployment method and use this repository (if this doenst work, you might have to fork the repository into your github account). And then click deploy. That should be it.

**Comment by Nastras** [comment]
Done, I have created app with link. 👍😘

I have now replaced the URL under Domains with myserverandport
https://XXXXX.herokuapp.com/calendar.ical?city_id=XXXXX&area_id=XXXXX

![C0633EDB-2391-4663-82B6-5692B0972B3B](https://user-images.githubusercontent.com/27686185/104109091-9022c000-52ca-11eb-9c08-319a1d8f5cc1.jpeg)



I tried to retrieve the data via Safari now i get again an error 😅

![104949B6-BE84-498D-A280-A096DB4F9CE5](https://user-images.githubusercontent.com/27686185/104109051-4fc34200-52ca-11eb-9846-03da9a3a4af7.jpeg)

**Comment by benzman81** [comment]
Great. Now you probably took the wrong id for area_id. It must be the areanid of the street, not the id of the street. Could you check?

**Comment by Nastras** [comment]
You were right I chose the ID with 5 digits instead of the one with 4 digits.
But now it worked and I can take the dates in the calendar 👍

I think it would be quite helpful for others if you explain it a little better in the description of how to set it up without own server via herocu. I think otherwise hardly anyone manages to implement your idea 😉

If you want we can maybe make an article on SmartApfel about it with a German tutorial or a tutorial in the Forum?

But it's a nice thing that I have the garbage dates now in the calendar so a big thank you for your quick help 😘

**Comment by Nastras** [comment]
I have created a tutorial in the forum. Would be happy if you can look over whether everything is correct? Thank you!

https://forum.smartapfel.de/forum/thread/7309-abfallkalender-einrichten-my-muell-ical/#post103689

**Comment by benzman81** [comment]
Awesome! Will integrate it in the readme whenever I find some time.
